#pragma once

#include <array>
#include <string_view>

// SRS 002 RR-5: the literal keyword table transcribed from
// applications/mkkeywordhash-legacy/mkkeywordhash.c's aKeywordTable[] (same
// order -- order affects the generator's output, see generator.hpp).
namespace sqlite::compiler::tooling::mkkeywordhash::detail {

struct keyword_source {
    std::string_view name;
    std::string_view token_type;
    // The legacy tool's mask exists to support SQLITE_OMIT_*-style
    // build-time configurability: a keyword with mask==0 is dropped from
    // the generated table. applications/mkkeywordhash-legacy/CMakeLists.txt
    // defines none of the SQLITE_OMIT_* macros, so every one of those
    // masks defaults nonzero (kept) in this workspace's actual generated
    // output -- except ORDERSET (the WITHIN keyword's mask alone), which
    // is gated the other way around by SQLITE_ENABLE_ORDERED_SET_AGGREGATES
    // (an opt-in flag also not defined here), so it defaults to 0 and
    // WITHIN is dropped. This table reproduces exactly that fixed
    // configuration rather than re-implementing arbitrary feature-flag
    // combinations nothing in this tree exercises.
    bool kept = true;
    int priority = 0;
};

inline constexpr std::array<keyword_source, 148> keyword_table{{
    {"ABORT", "TK_ABORT", true, 0},
    {"ACTION", "TK_ACTION", true, 0},
    {"ADD", "TK_ADD", true, 1},
    {"AFTER", "TK_AFTER", true, 0},
    {"ALL", "TK_ALL", true, 0},
    {"ALTER", "TK_ALTER", true, 0},
    {"ALWAYS", "TK_ALWAYS", true, 0},
    {"ANALYZE", "TK_ANALYZE", true, 0},
    {"AND", "TK_AND", true, 10},
    {"AS", "TK_AS", true, 10},
    {"ASC", "TK_ASC", true, 0},
    {"ATTACH", "TK_ATTACH", true, 1},
    {"AUTOINCREMENT", "TK_AUTOINCR", true, 0},
    {"BEFORE", "TK_BEFORE", true, 0},
    {"BEGIN", "TK_BEGIN", true, 1},
    {"BETWEEN", "TK_BETWEEN", true, 5},
    {"BY", "TK_BY", true, 10},
    {"CASCADE", "TK_CASCADE", true, 1},
    {"CASE", "TK_CASE", true, 5},
    {"CAST", "TK_CAST", true, 5},
    {"CHECK", "TK_CHECK", true, 1},
    {"COLLATE", "TK_COLLATE", true, 1},
    {"COLUMN", "TK_COLUMNKW", true, 1},
    {"COMMIT", "TK_COMMIT", true, 1},
    {"CONFLICT", "TK_CONFLICT", true, 0},
    {"CONSTRAINT", "TK_CONSTRAINT", true, 1},
    {"CREATE", "TK_CREATE", true, 2},
    {"CROSS", "TK_JOIN_KW", true, 3},
    {"CURRENT", "TK_CURRENT", true, 1},
    {"CURRENT_DATE", "TK_CTIME_KW", true, 1},
    {"CURRENT_TIME", "TK_CTIME_KW", true, 1},
    {"CURRENT_TIMESTAMP", "TK_CTIME_KW", true, 1},
    {"DATABASE", "TK_DATABASE", true, 0},
    {"DEFAULT", "TK_DEFAULT", true, 1},
    {"DEFERRED", "TK_DEFERRED", true, 1},
    {"DEFERRABLE", "TK_DEFERRABLE", true, 1},
    {"DELETE", "TK_DELETE", true, 10},
    {"DESC", "TK_DESC", true, 3},
    {"DETACH", "TK_DETACH", true, 0},
    {"DISTINCT", "TK_DISTINCT", true, 5},
    {"DO", "TK_DO", true, 2},
    {"DROP", "TK_DROP", true, 1},
    {"END", "TK_END", true, 1},
    {"EACH", "TK_EACH", true, 1},
    {"ELSE", "TK_ELSE", true, 2},
    {"ESCAPE", "TK_ESCAPE", true, 4},
    {"EXCEPT", "TK_EXCEPT", true, 4},
    {"EXCLUSIVE", "TK_EXCLUSIVE", true, 1},
    {"EXCLUDE", "TK_EXCLUDE", true, 1},
    {"EXISTS", "TK_EXISTS", true, 4},
    {"EXPLAIN", "TK_EXPLAIN", true, 1},
    {"FAIL", "TK_FAIL", true, 1},
    {"FILTER", "TK_FILTER", true, 4},
    {"FIRST", "TK_FIRST", true, 4},
    {"FOLLOWING", "TK_FOLLOWING", true, 4},
    {"FOR", "TK_FOR", true, 2},
    {"FOREIGN", "TK_FOREIGN", true, 1},
    {"FROM", "TK_FROM", true, 10},
    {"FULL", "TK_JOIN_KW", true, 3},
    {"GENERATED", "TK_GENERATED", true, 1},
    {"GLOB", "TK_LIKE_KW", true, 3},
    {"GROUP", "TK_GROUP", true, 5},
    {"GROUPS", "TK_GROUPS", true, 2},
    {"HAVING", "TK_HAVING", true, 5},
    {"IF", "TK_IF", true, 2},
    {"IGNORE", "TK_IGNORE", true, 1},
    {"IMMEDIATE", "TK_IMMEDIATE", true, 1},
    {"IN", "TK_IN", true, 10},
    {"INDEX", "TK_INDEX", true, 1},
    {"INDEXED", "TK_INDEXED", true, 0},
    {"INITIALLY", "TK_INITIALLY", true, 1},
    {"INNER", "TK_JOIN_KW", true, 1},
    {"INSERT", "TK_INSERT", true, 10},
    {"INSTEAD", "TK_INSTEAD", true, 1},
    {"INTERSECT", "TK_INTERSECT", true, 5},
    {"INTO", "TK_INTO", true, 10},
    {"IS", "TK_IS", true, 5},
    {"ISNULL", "TK_ISNULL", true, 5},
    {"JOIN", "TK_JOIN", true, 5},
    {"KEY", "TK_KEY", true, 1},
    {"LAST", "TK_LAST", true, 4},
    {"LEFT", "TK_JOIN_KW", true, 5},
    {"LIKE", "TK_LIKE_KW", true, 5},
    {"LIMIT", "TK_LIMIT", true, 3},
    {"MATCH", "TK_MATCH", true, 2},
    {"MATERIALIZED", "TK_MATERIALIZED", true, 12},
    {"NATURAL", "TK_JOIN_KW", true, 3},
    {"NO", "TK_NO", true, 2},
    {"NOT", "TK_NOT", true, 10},
    {"NOTHING", "TK_NOTHING", true, 1},
    {"NOTNULL", "TK_NOTNULL", true, 3},
    {"NULL", "TK_NULL", true, 10},
    {"NULLS", "TK_NULLS", true, 3},
    {"OF", "TK_OF", true, 3},
    {"OFFSET", "TK_OFFSET", true, 1},
    {"ON", "TK_ON", true, 1},
    {"OR", "TK_OR", true, 9},
    {"ORDER", "TK_ORDER", true, 10},
    {"OTHERS", "TK_OTHERS", true, 3},
    {"OUTER", "TK_JOIN_KW", true, 5},
    {"OVER", "TK_OVER", true, 3},
    {"PARTITION", "TK_PARTITION", true, 3},
    {"PLAN", "TK_PLAN", true, 0},
    {"PRAGMA", "TK_PRAGMA", true, 0},
    {"PRECEDING", "TK_PRECEDING", true, 3},
    {"PRIMARY", "TK_PRIMARY", true, 1},
    {"QUERY", "TK_QUERY", true, 0},
    {"RAISE", "TK_RAISE", true, 1},
    {"RANGE", "TK_RANGE", true, 3},
    {"RECURSIVE", "TK_RECURSIVE", true, 3},
    {"REFERENCES", "TK_REFERENCES", true, 1},
    {"REGEXP", "TK_LIKE_KW", true, 3},
    {"REINDEX", "TK_REINDEX", true, 1},
    {"RELEASE", "TK_RELEASE", true, 1},
    {"RENAME", "TK_RENAME", true, 1},
    {"REPLACE", "TK_REPLACE", true, 10},
    {"RESTRICT", "TK_RESTRICT", true, 1},
    {"RETURNING", "TK_RETURNING", true, 10},
    {"RIGHT", "TK_JOIN_KW", true, 0},
    {"ROLLBACK", "TK_ROLLBACK", true, 1},
    {"ROW", "TK_ROW", true, 1},
    {"ROWS", "TK_ROWS", true, 1},
    {"SAVEPOINT", "TK_SAVEPOINT", true, 1},
    {"SELECT", "TK_SELECT", true, 10},
    {"SET", "TK_SET", true, 10},
    {"TABLE", "TK_TABLE", true, 1},
    {"TEMP", "TK_TEMP", true, 1},
    {"TEMPORARY", "TK_TEMP", true, 1},
    {"THEN", "TK_THEN", true, 3},
    {"TIES", "TK_TIES", true, 3},
    {"TO", "TK_TO", true, 3},
    {"TRANSACTION", "TK_TRANSACTION", true, 1},
    {"TRIGGER", "TK_TRIGGER", true, 1},
    {"UNBOUNDED", "TK_UNBOUNDED", true, 3},
    {"UNION", "TK_UNION", true, 3},
    {"UNIQUE", "TK_UNIQUE", true, 1},
    {"UPDATE", "TK_UPDATE", true, 10},
    {"USING", "TK_USING", true, 8},
    {"VACUUM", "TK_VACUUM", true, 1},
    {"VALUES", "TK_VALUES", true, 10},
    {"VIEW", "TK_VIEW", true, 1},
    {"VIRTUAL", "TK_VIRTUAL", true, 1},
    {"WHEN", "TK_WHEN", true, 1},
    {"WHERE", "TK_WHERE", true, 10},
    {"WINDOW", "TK_WINDOW", true, 3},
    {"WITH", "TK_WITH", true, 4},
    {"WITHIN", "TK_WITHIN", false, 1}, // mask == ORDERSET == 0 by default (see comment above)
    {"WITHOUT", "TK_WITHOUT", true, 1},
}};

} // namespace sqlite::compiler::tooling::mkkeywordhash::detail
