#!/usr/bin/env bash
# SRS 002 RR-7/TR-1: runs a legacy generator application and its complete
# C++ replacement (RR-5) with equivalent invocations and diffs their
# output, after normalizing away the one documented, reviewed exception
# TR-1 explicitly anticipates ("e.g., a timestamp comment the legacy tool
# emits that is deliberately omitted by the replacement"): each tool's own
# "Automatically generated... see <path> for details" provenance-banner
# line, which necessarily differs since the new tool isn't generated by the
# legacy tool's path. Every other line must match exactly -- RR-7 requires
# full agreement for generator applications, unlike RR-9's library-level
# comparison, which is scope-restricted.
#
# Usage: check-generator-parity.sh '<legacy invocation>' '<new-track invocation>'
# Each invocation is a shell command string (may itself be a pipeline, e.g.
# "cat a b | some-tool"), run via `bash -c`.
set -euo pipefail

if [ "$#" -ne 2 ]; then
    echo "usage: check-generator-parity.sh '<legacy invocation>' '<new-track invocation>'" >&2
    exit 2
fi

LEGACY_CMD="$1"
NEW_CMD="$2"

# Matches the three known banner-line shapes across mkkeywordhash/
# mkopcodec/mkopcodeh (legacy and new-track alike) as whole-line
# replacements, rather than trying to extract just the differing path
# substring -- simpler and exact, since each tool's banner is always
# either "**   <path>" (mkkeywordhash) or "/* See the <path> script for
# details[.] */" (mkopcodec/mkopcodeh).
normalize() {
    sed -E \
        -e 's#^\*\*[[:space:]]+(sqlite/)?tool/mk[A-Za-z0-9_]*\.c$#<GENERATOR-PROVENANCE>#' \
        -e 's#^\*\*[[:space:]]+applications/mk[A-Za-z0-9_-]+$#<GENERATOR-PROVENANCE>#' \
        -e 's#^/\* See the (tool|applications)/mk[A-Za-z0-9_./-]* script for details\.? \*/$#<GENERATOR-PROVENANCE>#'
}

LEGACY_OUT="$(bash -c "$LEGACY_CMD" | normalize)"
NEW_OUT="$(bash -c "$NEW_CMD" | normalize)"

if [ "$LEGACY_OUT" != "$NEW_OUT" ]; then
    echo "error: generator output diverges (SRS 002 RR-7) beyond the documented provenance-banner exception (TR-1)" >&2
    diff <(printf '%s\n' "$LEGACY_OUT") <(printf '%s\n' "$NEW_OUT") >&2 || true
    exit 1
fi

echo "generator parity check passed"
